# jpa
spring:
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
# ucenter
apzda:
  ucenter:
    security:
      resources:
        auditlog:
          name: "{resource.AuditLog}"
          description: "{resource.AuditLogDesc}"
          actions: r,d
          privileges:
            "[*:auditlog.*]":
              name: AuditLogFullAccess
              description: "{privilege.AuditLogFullAccessDesc}"
            "[r:auditlog.*]":
              name: AuditLogReadOnlyAccess
              description: "{privilege.AuditLogReadOnlyAccessDesc}"
