spring:
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    hibernate:
      ddl-auto: validate

apzda:
  ucenter:
    server:
      authenticator: com.apzda.cloud.uc.security.mfa.GoogleTotpAuthenticator
    security:
      resources:
        user:
          name: "{resource.User}"
          description: "{resource.UserDesc}"
          actions: c,r,u,d,kickoff
          explorer: com.apzda.cloud.uc.resource.UserIdExplorer
          privileges:
            "[*:user.*]":
              name: UserFullAccess
              description: "{privilege.UserFullAccessDesc}"
            "[r:user.*]":
              name: UserReadOnlyAccess
              description: "{privilege.UserReadOnlyAccessDesc}"
            "[kickoff:user.*]":
              name: "{privilege.KickoffUser}"
              description: "{privilege.KickoffUserDesc}"
        role:
          name: "{resource.Role}"
          description: "{resource.RoleDesc}"
          privileges:
            "[*:role.*]":
              name: RoleFullAccess
              description: "{privilege.RoleFullAccessDesc}"
            "[r:role.*]":
              name: RoleReadOnlyAccess
              description: "{privilege.RoleReadOnlyAccessDesc}"
        privilege:
          name: "{resource.Privilege}"
          description: "{resource.PrivilegeDesc}"
          privileges:
            "[*:privilege.*]":
              name: PrivilegeFullAccess
              description: "{privilege.PrivilegeFullAccessDesc}"
            "[r:privilege.*]":
              name: PrivilegeReadOnlyAccess
              description: "{privilege.PrivilegeReadOnlyAccessDesc}"
          children:
            resource:
              name: "{resource.Resource}"
              description: "{resource.ResourceDesc}"
              actions: r
      privileges:
        "[*:*]":
          name: "{privilege.AllPrivileges}"
          description: "{privilege.AllPrivilegesDesc}"
        RUNAS:
          name: "{privilege.RunAs}"
          description: "{privilege.RunAsDesc}"
          type: authority
        SIMPLE_USER:
          name: "{privilege.SimpleUser}"
          type: authority
          description: "{privilege.SimpleUserDesc}"
      roles:
        sa:
          name: "{role.SuperAdministrator}"
          description: "{role.SuperAdministratorDesc}"
        admin:
          name: "{role.Administrator}"
          description: "{role.AdministratorDesc}"
        user:
          name: "{role.AuthenticatedUser}"
          description: "{role.AuthenticatedUserDesc}"
